MODULE TIME
    IMPLICIT NONE
    PUBLIC
CONTAINS
    ! $ FUNCTION ISECS(IHMS) (WLH)
    ! $  CONVERT HHMMSS TO SECONDS
    ! $ IHMS = INPUT (I) TIME
    ! $$ ISECS=COMPUTAT
    FUNCTION ISECS(IHMS)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: IHMS
        INTEGER :: IH,IS,IM,ISECS
        IH=IHMS/10000
        IS=IHMS-10000*IH
        IM=IS/100
        IS=IS-100*IM
        ISECS=3600*IH+60*IM+IS
        RETURN
    END FUNCTION ISECS

    ! $ FUNCTION IHMS(ISEC) (WLH)
    ! $ CONVERT SECONDS TO HHMMSS
    ! $ ISEC = INPUT (I) TIME
    ! $$ IHMS=COMPUTAT
    FUNCTION IHMS(ISEC)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: ISEC
        INTEGER :: IH,IS,IM,IHMS
        IH=ISEC/3600
        IS=ISEC-3600*IH
        IM=IS/60
        IS=IS-60*IM
        IHMS=10000*IH+100*IM+IS
        RETURN
    END FUNCTION IHMS

    ! $ FUNCTION IDAYS(IYD) (WLH)
    ! $ CONVERT FROM YYDDD TO DAYS SINCE JAN. 1, 1900
    ! $ IYD = INPUT (I) DATE
    ! $$ IDAYS=COMPUTAT
    FUNCTION IDAYS(IYD)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: IYD
        INTEGER :: IY, ID, IDAYS
        IY=IYD/1000
        ID=IYD-1000*IY
        IDAYS=365*IY+(IY-1)/4+ID
        RETURN
    END FUNCTION IDAYS

    ! $ FUNCTION IYYDDD(IDAY) (WLH)
    ! $ CONVERT FROM DAYS SINCE JAN. 1, 1900 TO YYDDD
    ! $ IDAY = INPUT (I) DATE
    ! $$ IYYDDD=COMPUTAT
    FUNCTION IYYDDD(IDAY)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: IDAY
        INTEGER :: IY, ID, IYYDDD
        IY=(4*IDAY)/1461
        ID=IDAY-(365*IY+(IY-1)/4)
        IYYDDD=IY*1000+ID
        RETURN
    END FUNCTION IYYDDD
END MODULE TIME
